[package]
name = "homebank_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "1.0.5"
thiserror = "1.0.30"
xml-rs = "0.8.4"
